export * from './IBaseController'
export * from './IDeleteBaseController'
export * from './IInsertBaseController'
export * from './IQueryCondition'
export * from './IReadBaseController'
export * from './IUpdateBaseController'
